### ISSUE TITLE
Mention the Python Version for easier deployment

### ISSUE THREAD

**Issue by Wakeelfahmed** [VAST-AI-Research/TripoSR#107]
I'm unable to deploy on kaggle (py version: Python 3.10.13), plz mention the py version u have deployed this project.

/kaggle/working/TripoSR
Traceback (most recent call last):
  File "/kaggle/working/TripoSR/run.py", line 12, in <module>
    from tsr.system import TSR
  File "/kaggle/working/TripoSR/tsr/system.py", line 16, in <module>
    from .models.isosurface import MarchingCubeHelper
  File "/kaggle/working/TripoSR/tsr/models/isosurface.py", line 6, in <module>
    from torchmcubes import marching_cubes
  File "/opt/conda/lib/python3.10/site-packages/torchmcubes/__init__.py", line 2, in <module>
    import torchmcubes_module as mc
ImportError: /opt/conda/lib/python3.10/site-packages/torchmcubes_module.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl3cow11cow_deleterEPv

**Comment by Wakeelfahmed** [comment]
Alright I have been able to run its easily on Python 3.9 (1st tried 3.8 but was not working)
