### ISSUE TITLE
help：module 'torchmcubes_module' has no attribute 'mcubes_cuda'. Did you mean: 'mcubes_cpu'?

### ISSUE THREAD

**Issue by tiandaoyuxi** [VAST-AI-Research/TripoSR#11]
(venv) D:\TripoSR>python gradio_app.py
D:\TripoSR\venv\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
D:\TripoSR\venv\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
D:\TripoSR\tsr\models\transformer\attention.py:629: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  hidden_states = F.scaled_dot_product_attention(
Traceback (most recent call last):
  File "D:\TripoSR\venv\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\TripoSR\venv\lib\site-packages\gradio\route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\TripoSR\venv\lib\site-packages\gradio\blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "D:\TripoSR\venv\lib\site-packages\gradio\blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\TripoSR\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\TripoSR\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\TripoSR\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\TripoSR\venv\lib\site-packages\gradio\utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "D:\TripoSR\gradio_app.py", line 60, in generate
    mesh = model.extract_mesh(scene_codes)[0]
  File "D:\TripoSR\tsr\system.py", line 185, in extract_mesh
    v_pos, t_pos_idx = self.isosurface_helper(-(density - threshold))
  File "D:\TripoSR\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\TripoSR\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TripoSR\tsr\models\isosurface.py", line 45, in forward
    v_pos, t_pos_idx = self.mc_func(level.detach(), 0.0)
  File "D:\TripoSR\venv\lib\site-packages\torchmcubes\__init__.py", line 12, in marching_cubes
    return mc.mcubes_cuda(vol, thresh)
AttributeError: module 'torchmcubes_module' has no attribute 'mcubes_cuda'. Did you mean: 'mcubes_cpu'?

**Comment by bennyguo** [comment]
Are you using `venv` to set up the environment? Could you please try `virtualenv` instead?

**Comment by tiandaoyuxi** [comment]
> Are you using `venv` to set up the environment? Could you please try `virtualenv` instead?

yes， i using venv .
(venv) D:\TripoSR>python gradio_app.py
