### ISSUE TITLE
Running error after model load. Please advice!

### ISSUE THREAD

**Issue by zappazack** [VAST-AI-Research/TripoSR#17]
2024-03-05 13:55:09,053 - INFO - Initializing model finished in 3986.39ms.
2024-03-05 13:55:09,053 - INFO - Processing images ...
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-03-05 13:55:13,743 - INFO - Processing images finished in 4689.23ms.
2024-03-05 13:55:13,743 - INFO - Running image 1/1 ...
2024-03-05 13:55:13,743 - INFO - Running model ...
2024-03-05 13:55:14,634 - INFO - Running model finished in 891.16ms.
2024-03-05 13:55:14,634 - INFO - Exporting mesh ...
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\TripoSR\run.py", line 154, in <module>
    meshes = model.extract_mesh(scene_codes)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 185, in extract_mesh
    v_pos, t_pos_idx = self.isosurface_helper(-(density - threshold))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\models\isosurface.py", line 45, in forward
    v_pos, t_pos_idx = self.mc_func(level.detach(), 0.0)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torchmcubes\__init__.py", line 12, in marching_cubes
    return mc.mcubes_cuda(vol, thresh)
AttributeError: module 'torchmcubes_module' has no attribute 'mcubes_cuda'. Did you mean: 'mcubes_cpu'?

**Comment by pookiefoof** [comment]
Please see if discussions in  #1  helps

**Comment by zappazack** [comment]
> Please see if discussions in #1 helps

Thx for the answer I am using not a venv after this command pip install wheel setuptools pip --upgrade I am receiving the follwing error:
PS C:\Users\User\Documents\GitHub\TripoSR> python run.py examples/chair.png --output-dir output/
2024-03-05 15:52:20,805 - INFO - Initializing model ...
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\TripoSR\run.py", line 103, in <module>
    model = TSR.from_pretrained(
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 68, in from_pretrained
    model = cls(cfg)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\utils.py", line 58, in __init__
    self.configure(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 74, in configure
    self.image_tokenizer = find_class(self.cfg.image_tokenizer_cls)(
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\utils.py", line 27, in find_class
    module = importlib.import_module(module_string, package=None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\models\tokenizers\image.py", line 7, in <module>
    from transformers.models.vit.modeling_vit import ViTModel
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.19.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

**Comment by zappazack** [comment]
> Please see if discussions in #1 helps

Sadly after this step I can even not run it anymore through CPU enforcement.

**Comment by bennyguo** [comment]
@zappazack After `pip install wheel setuptools pip --upgrade`, could you please try to install the dependencies again and try if it works?

**Comment by zappazack** [comment]
> @zappazack After `pip install wheel setuptools pip --upgrade`, could you please try to install the dependencies again and try if it works?

Done as I have had the same in mind but now regular command and --device cpu are showing now this problem:
PS C:\Users\User\Documents\GitHub\TripoSR> python run.py examples/chair.png --output-dir output/
2024-03-05 16:31:32,414 - INFO - Initializing model ...
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\TripoSR\run.py", line 103, in <module>
    model = TSR.from_pretrained(
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 68, in from_pretrained
    model = cls(cfg)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\utils.py", line 58, in __init__
    self.configure(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 74, in configure
    self.image_tokenizer = find_class(self.cfg.image_tokenizer_cls)(
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\utils.py", line 27, in find_class
    module = importlib.import_module(module_string, package=None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\models\tokenizers\image.py", line 7, in <module>
    from transformers.models.vit.modeling_vit import ViTModel
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.19.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
PS C:\Users\User\Documents\GitHub\TripoSR> python run.py --device cpu examples/chair.png --output-dir output/
2024-03-05 16:32:03,662 - INFO - Initializing model ...
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\TripoSR\run.py", line 103, in <module>
    model = TSR.from_pretrained(
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 68, in from_pretrained
    model = cls(cfg)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\utils.py", line 58, in __init__
    self.configure(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 74, in configure
    self.image_tokenizer = find_class(self.cfg.image_tokenizer_cls)(
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\utils.py", line 27, in find_class
    module = importlib.import_module(module_string, package=None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\models\tokenizers\image.py", line 7, in <module>
    from transformers.models.vit.modeling_vit import ViTModel
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.19.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

**Comment by zappazack** [comment]
> @zappazack After `pip install wheel setuptools pip --upgrade`, could you please try to install the dependencies again and try if it works?

I was able to restore CPU enfoecement by these commands in base path:
"Developer Console.cmd"

python -m pip install --upgrade pip --force-reinstall
pip install transformers -U
pip install accelerate
pip install transformers -U

Message appearing:
PS C:\Users\User\Documents\GitHub\TripoSR> python run.py --device cpu examples/chair.png --output-dir output/
2024-03-05 16:41:46,575 - INFO - Initializing model ...
2024-03-05 16:41:49,670 - INFO - Initializing model finished in 3094.14ms.
2024-03-05 16:41:49,670 - INFO - Processing images ...
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-03-05 16:41:50,170 - INFO - Processing images finished in 500.04ms.
2024-03-05 16:41:50,170 - INFO - Running image 1/1 ...
2024-03-05 16:41:50,170 - INFO - Running model ...
2024-03-05 16:42:01,568 - INFO - Running model finished in 11398.49ms.
2024-03-05 16:42:01,568 - INFO - Exporting mesh ...
2024-03-05 16:42:26,337 - INFO - Exporting mesh finished in 24768.38ms.

Maybe its possible to get some hint whats wrong with the normal command which leads to:
PS C:\Users\User\Documents\GitHub\TripoSR> python run.py examples/chair.png --output-dir output/
2024-03-05 16:50:55,482 - INFO - Initializing model ...
2024-03-05 16:50:58,765 - INFO - Initializing model finished in 3282.83ms.
2024-03-05 16:50:58,765 - INFO - Processing images ...
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-03-05 16:50:59,265 - INFO - Processing images finished in 500.20ms.
2024-03-05 16:50:59,265 - INFO - Running image 1/1 ...
2024-03-05 16:50:59,265 - INFO - Running model ...
2024-03-05 16:50:59,984 - INFO - Running model finished in 719.13ms.
2024-03-05 16:50:59,984 - INFO - Exporting mesh ...
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\TripoSR\run.py", line 154, in <module>
    meshes = model.extract_mesh(scene_codes)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\system.py", line 185, in extract_mesh
    v_pos, t_pos_idx = self.isosurface_helper(-(density - threshold))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\TripoSR\tsr\models\isosurface.py", line 45, in forward
    v_pos, t_pos_idx = self.mc_func(level.detach(), 0.0)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torchmcubes\__init__.py", line 12, in marching_cubes
    return mc.mcubes_cuda(vol, thresh)
AttributeError: module 'torchmcubes_module' has no attribute 'mcubes_cuda'. Did you mean: 'mcubes_cpu'?

**Comment by zappazack** [comment]
> @zappazack After `pip install wheel setuptools pip --upgrade`, could you please try to install the dependencies again and try if it works?

I will close this issue, thx for your support, I appreciate it!! This is how it worked for me:
1. Complete deinstalltion of my python 3.10.10 including cache
2. Reinstallation of python 3.10.10
3. pip install --upgrade pip
4. pip install wheel setuptools pip --upgrade
Due to error message of changing pip
In my case I have had to run:
5. C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m pip install wheel setuptools pip --upgrade
6. pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
7. pip install -r requirements.txt
8. pip install gradio
9. python gradio_app.py
10. In Browser f.e. http://127.0.0.1:7860
Everything works!!
