### ISSUE TITLE
Increase texture resolution

### ISSUE THREAD

**Issue by rkfg** [VAST-AI-Research/TripoSR#22]
Is there any way to improve the texture? It's very low res and often buggy. The mesh quality is fine though.

![2024-03-06_02-55-47](https://github.com/VAST-AI-Research/TripoSR/assets/184066/ce45e37d-d144-40c3-95ec-e9845eeefb2f)

I played with foreground ratio but can't make it any better. I also changed the chunk size and I don't see any noticeable effect.

**Comment by nagolinc** [comment]
I've just been projecting the original image onto the front of the mesh

```
def projectImg(mesh, img_path, save_path="static/samples/",foreground_ratio=0.85):
    modified_img_path img_path
    
    # Load the modified image to get its size for UV mapping calculations
    modified_image = Image.open(modified_img_path)
    width, height = modified_image.size
    
    # Calculate UVs for the transparent area
    # Assuming the transparent area is at the bottom right corner
    uv_transparent = np.array([(width - 100) / width, (height - 100) / height])
    
    # Identify front and back faces based on their normals
    forward_normal = np.array([0, 0, 1])
    dot_product = mesh.face_normals.dot(forward_normal)
    front_faces = dot_product < 0
    back_faces = ~front_faces
    
    # Compute UV coordinates for all vertices based on their XY positions
    uv_bounds_min, uv_bounds_max = -0.5/foreground_ratio, 0.5/foreground_ratio
    uv_coords = (mesh.vertices[:, [0, 1]] - uv_bounds_min) / (uv_bounds_max - uv_bounds_min)
    
    # Adjust UV coordinates for back faces to map to the transparent area
    for face in mesh.faces[back_faces]:
        uv_coords[face] = uv_transparent  # Map back face vertices to the transparent area
    
    # Apply the texture and UV mapping
    texture = trimesh.visual.texture.TextureVisuals(image=modified_image)
    mesh.visual = texture
    mesh.visual.uv = uv_coords
    
    # Export the mesh as GLB
    #mesh_filename = save_path + 'textured_mesh_with_transparency.glb'
    mesh_filename = getFilename(save_path, "glb")
    mesh.export(mesh_filename, file_type='glb')
    
    return mesh_filename
    ```
    
![Screenshot 2024-03-06 090910](https://github.com/VAST-AI-Research/TripoSR/assets/7775917/78f51462-00f5-4e6c-b732-2fd3cdf0de13)

    Obviously not optimal, and doesn't generate colors for the back/side.  Does anyone have a solution for dumping the vertex colors to a uv texture (then maybe we could try and enhance them with stableDiffusion or something)

**Comment by CyberTimon** [comment]
I would also like to know how to increase the generated texture resolution automatically. +1

**Comment by al3dv2** [comment]
@nagolinc you can unwrap the model in blender then use Stable Projectorz for project hd texture on the model but the problem you get bad result in some angles the best could be to just generate models with more geometry

**Comment by al3dv2** [comment]
@mrbid Yes good idea thanks for the links

**Comment by al3dv2** [comment]
@mrbid The best for upscaling is to use controlnet Tile, there's also SUPIR

**Comment by al3dv2** [comment]
Something that could works too is to duplicate the mesh in Blender make a clean unwrap of the duplicate for get a great uv texture, baking the vertex color on the clean unwrap and then upscale with controlnet tile or SUPIR the uv texture

**Comment by CyberTimon** [comment]
Maybe a combination of projecting and the generated will work good together for the front and the back?

**Comment by thatname** [comment]
I fixed this, you can try #68

**Comment by al3dv2** [comment]
> I fixed this, you can try #68
@thatname 
I have the same problem than mrbid I can't go above 96 and I'm using gpu mode : 

Traceback (most recent call last):
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\route_utils.py", line 258, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\blocks.py", line 1710, in process_api
    result = await self.call_function(
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\blocks.py", line 1250, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\utils.py", line 693, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Shadow\Desktop\TripoSR\gradio_app.py", line 63, in generate
    mesh = model.extract_mesh(scene_codes, resolution=mc_resolution)[0]
  File "C:\Users\Shadow\Desktop\TripoSR\tsr\system.py", line 166, in extract_mesh
    v_pos, color, t_pos_idx = self.renderer.block_based_marchingcube(self.decoder.to(scene_codes.device),
  File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\nerf_renderer.py", line 91, in block_based_marchingcube
    v_color = self.query_triplane(decoder, v_pos, triplane, False)["color"]
  File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\nerf_renderer.py", line 142, in query_triplane
    net_out = chunk_batch(_query_chunk, self.chunk_size, positions)
  File "C:\Users\Shadow\Desktop\TripoSR\tsr\utils.py", line 169, in chunk_batch
    out_chunk = func(
  File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\nerf_renderer.py", line 138, in _query_chunk
    net_out: Dict[str, torch.Tensor] = decoder(out)
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\network_utils.py", line 121, in forward
    features = features.reshape(*inp_shape, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by thatname** [comment]
> > I fixed this, you can try #68
> > @thatname
> > I have the same problem than mrbid I can't go above 96 and I'm using gpu mode :
> 
> Traceback (most recent call last): File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\queueing.py", line 501, in call_prediction output = await route_utils.call_process_api( File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\route_utils.py", line 258, in call_process_api output = await app.get_blocks().process_api( File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\blocks.py", line 1710, in process_api result = await self.call_function( File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\blocks.py", line 1250, in call_function prediction = await anyio.to_thread.run_sync( File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\anyio\to_thread.py", line 56, in run_sync return await get_async_backend().run_sync_in_worker_thread( File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\anyio_backends_asyncio.py", line 2144, in run_sync_in_worker_thread return await future File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\anyio_backends_asyncio.py", line 851, in run result = context.run(func, *args) File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\gradio\utils.py", line 693, in wrapper response = f(*args, **kwargs) File "C:\Users\Shadow\Desktop\TripoSR\gradio_app.py", line 63, in generate mesh = model.extract_mesh(scene_codes, resolution=mc_resolution)[0] File "C:\Users\Shadow\Desktop\TripoSR\tsr\system.py", line 166, in extract_mesh v_pos, color, t_pos_idx = self.renderer.block_based_marchingcube(self.decoder.to(scene_codes.device), File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\nerf_renderer.py", line 91, in block_based_marchingcube v_color = self.query_triplane(decoder, v_pos, triplane, False)["color"] File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\nerf_renderer.py", line 142, in query_triplane net_out = chunk_batch(_query_chunk, self.chunk_size, positions) File "C:\Users\Shadow\Desktop\TripoSR\tsr\utils.py", line 169, in chunk_batch out_chunk = func( File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\nerf_renderer.py", line 138, in _query_chunk net_out: Dict[str, torch.Tensor] = decoder(out) File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "C:\Users\Shadow\Desktop\TripoSR\tripo\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) File "C:\Users\Shadow\Desktop\TripoSR\tsr\models\network_utils.py", line 121, in forward features = features.reshape(*inp_shape, -1) RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

I changed the color sampling code to fix it, please try again?

**Comment by al3dv2** [comment]
> I changed the color sampling code to fix it, please try again?


It's works thanks! I have another question do you know how to add your code to the comfyui version ? https://github.com/flowtyone/ComfyUI-Flowty-TripoSR
Because the comfyui version generate 3d models faster on my computer

**Comment by thatname** [comment]
> > I changed the color sampling code to fix it, please try again?
> 
> It's works thanks! I have another question do you know how to add your code to the comfyui version ? https://github.com/flowtyone/ComfyUI-Flowty-TripoSR Because the comfyui version generate 3d models faster on my computer
Copy the 'tsr' folder from my repo may work.
But their code used another marching cube package, maybe it can generate 1024 directly.

**Comment by al3dv2** [comment]
@thatname I tried but it's doesn't works I got a error message : ERROR:root:* TripoSRSampler 274:
ERROR:root:  - Return type mismatch between linked nodes: model, TRIPOSR_MODEL !=

**Comment by al3dv2** [comment]
Someone have release a script for increase the resolution of the texture https://github.com/ejones/triposr-texture-gen?tab=readme-ov-file
