### ISSUE TITLE
Cannot load model 

### ISSUE THREAD

**Issue by aquarter147** [VAST-AI-Research/TripoSR#51]
2024-03-11 10:32:52,933 - INFO - Initializing model ...
Traceback (most recent call last):
  File "/mnt/thaoanh/img23d/TripoSR/run.py", line 109, in <module>
    model = TSR.from_pretrained(
  File "/mnt/thaoanh/img23d/TripoSR/tsr/system.py", line 69, in from_pretrained
    model = cls(cfg)
  File "/mnt/thaoanh/img23d/TripoSR/tsr/utils.py", line 57, in __init__
    self.cfg = parse_structured(self.Config, cfg)
  File "/mnt/thaoanh/img23d/TripoSR/tsr/utils.py", line 20, in parse_structured
    scfg = OmegaConf.merge(OmegaConf.structured(fields), cfg)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 119, in structured
    return OmegaConf.create(obj, parent, flags)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 172, in create
    return OmegaConf._create_impl(
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 861, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 832, in _create_impl
    return DictConfig(
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 113, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 97, in __init__
    self._set_value(content, flags=flags)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 638, in _set_value
    raise e
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 635, in _set_value
    self._set_value_impl(value, flags)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 665, in _set_value_impl
    data = get_structured_config_data(value, allow_objects=ao)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 445, in get_structured_config_data
    return get_dataclass_data(obj, allow_objects=allow_objects)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 373, in get_dataclass_data
    format_and_raise(
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/_utils.py", line 365, in get_dataclass_data
    d[name] = _maybe_wrap(
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1041, in _maybe_wrap
    return _node_wrap(
  File "/home/thaoanh/miniconda3/envs/gen/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1023, in _node_wrap
    raise ValidationError(f"Unexpected object type: {type_str(type_)}")
omegaconf.errors.ValidationError: Unexpected object type: dict
    full_key: image_tokenizer
    object_type=Config

**Comment by pookiefoof** [comment]
Could you make sure the model checkpoint and config files were successfully downloaded? Also, could you provide you build environment?
